apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  labels:
    app: jenkins-demo
spec:
  replicas: 1
  selector:
      matchLabels:
        app: jenkins-demo
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: krisbai1991/jenkins-demo:<BUILD_TAG>
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
